### ISSUE TITLE
Return list from method query(queryObject) 

### ISSUE THREAD

**Issue by bampakoa** [rangle/hackstack#41]
Hi,

Is it possible to return a whole list, instead of the first object, from method **query(queryObject)**?

Thanks

**Comment by brianolynyk** [comment]
Hi,

Would a random list of items be acceptable?  My worry here is getting into actually implementing a query language.

Thanks.

**Comment by bampakoa** [comment]
What do you mean by "random list"? Could you please elaborate?

Thanks.

**Comment by brianolynyk** [comment]
The function would return a list instead of a single object like it does now.  But the list would be built from randomly selected/generated objects based on the data you initialized the hackstack with.

Does that help?

Thanks.

**Comment by bampakoa** [comment]
That would be fine. Thanks!

**Comment by bampakoa** [comment]
Hi,

Is there any update on this request?

Thanks

**Comment by bampakoa** [comment]
@brianolynyk Its been a long time ago since this is issue is active. Is there any chance that you are going to implement it? I could try and submit a PR if you want otherwise.
